default-config: &default-config
  working_directory: ~/repo

deploy-steps: &deploy-steps
  steps:
    - attach_workspace:
        at: .
    - run:
        name: Install deploy dependencies
        command: |
          npm install --no-save

    - run:
        name: Start Node Server
        command: npm start
        background: true

jobs:
  cypress-test:
    docker:
    - image: cypress/base:10
    steps:
    - checkout
    - restore_cache:
        keys:
          - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          - deps-{{ checksum "package.json" }}-
          - deps-
    - run:
        name: Install dependencies
        command: |
          npm install --no-save
    - run:
        name: Start Node Server
        command: npm start
        background: true
    - run:
        name: Run Cypress
        command: |
          $(yarn bin)/cypress run

  deploy-dev:
      <<: *default-config
      <<: *deploy-steps

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-dev:
          filters:
            branches:
              ignore:
                - main
      - cypress-test
