version: 2.1

workflows:
  build:
    jobs:
      cypress-test:
        docker:
        - image: cypress/base:10
        steps:
        - checkout
        - restore_cache:
            keys:
              - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
              - deps-{{ checksum "package.json" }}-
              - deps-
        - run:
            name: Start Node Server
            command: |
              npm start
        - run:
            name: Install dependencies
            command: |
              npm install --no-save
        - run:
            name: Run Cypress
            command: |
              npx cypress run
