version: 2.1

jobs:
  cypress-test:
    docker:
    - image: cypress/base:10
    steps:
    - checkout
    - restore_cache:
        keys:
          - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          - deps-{{ checksum "package.json" }}-
          - deps-
    - run:
        name: Start Node Server
        command: |
          npm start
    - run:
        name: Install dependencies
        command: |
          npm install --no-save

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - cypress-test:
