default-config: &default-config
  working_directory: ~/repo

jobs:
  cypress-test:
    docker:
    - image: cypress/base:10
    steps:
    - checkout
    - restore_cache:
        keys:
          - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          - deps-{{ checksum "package.json" }}-
          - deps-
    - run:
        name: Install dependencies
        command: |
          npm install --no-save
    - run:
        name: Start Node Server
        command: |
          npm start
          background: true
    - run:
        name: Run Cypress
        command: |
          cypress run

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - cypress-test
